name: CI_windows

on: [push, pull_request]

env:
  CI: "ON"
  CTEST_TIME_TIMEOUT: "5"  # some failures hang forever

jobs:
  Build:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v1

    - name: Install fypp
      run: pip install fypp

    - run: cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -Wdev -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_Fortran_FLAGS_DEBUG="-Wall -Wextra -Wimplicit-interface -fPIC -g -fcheck=all -fbacktrace"

      env:
        FC: gfortran
        CC: gcc
        CXX: g++

    - name: CMake build
      run: cmake --build build --parallel

    - name: catch build fail
      run: cmake --build build --verbose --parallel 1
      if: failure()

    - name: CTest
      run: ctest --output-on-failure --parallel -V -LE quadruple_precision
      working-directory: build

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: WindowsCMakeTestlog
        path: build/Testing/Temporary/LastTest.log
