name: CI

on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install GFortran
      run: sudo apt-get install gfortran
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: test
      run: ctest --output-on-failure

  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install GFortran
      run: conda install -c conda-forge gfortran_osx-64
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: test
      run: ctest --output-on-failure

  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: cmake -G "Visual Studio 16 2019" .
    - name: make
      run: cmake --build .
    - name: test
      run: ctest --output-on-failure
